/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int sumFibonacciEvenTerms(int upper_limit)
{
    int term1 = 1;
    int term2 = 2;
    cout << "1 2 ";
    int running_sum = 2;
    while(term2 < upper_limit)
    {
        int new_term = term1 + term2;
        term1 = term2;
        term2 = new_term;
        if(term2 > upper_limit)
            break;
        cout << new_term << " ";
        if(term2 % 2 == 0)  
            running_sum += term2;
    }
    cout << endl;
    return running_sum;
}

int main(int argc, char *argv[])
{
    cout << sumFibonacciEvenTerms(atoi(argv[1]));
    
    return 0;
}
